alertmanager:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - alertmanager.papichulo
    paths:
      - /
grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.papichulo
    path: /
prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.papichulo
    paths:
      - /
